//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eclj.UtilityBelt.pt_BR.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eclj.UtilityBelt.pt_BR.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string isCNPJ_error_default {
            get {
                return ResourceManager.GetString("isCNPJ_error_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first digit of value is not equal to the first digit verifier..
        /// </summary>
        public static string isCNPJ_error_firstDigit {
            get {
                return ResourceManager.GetString("isCNPJ_error_firstDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value contain invalid characters.
        /// </summary>
        public static string isCNPJ_error_invalidCharacters {
            get {
                return ResourceManager.GetString("isCNPJ_error_invalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value does not contains fourteen characters.
        /// </summary>
        public static string isCNPJ_error_notFourteenCharacters {
            get {
                return ResourceManager.GetString("isCNPJ_error_notFourteenCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is null or empty..
        /// </summary>
        public static string isCNPJ_error_nullOrEmpty {
            get {
                return ResourceManager.GetString("isCNPJ_error_nullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second digit of value is not equal to the second digit verifier..
        /// </summary>
        public static string isCNPJ_error_secondDigit {
            get {
                return ResourceManager.GetString("isCNPJ_error_secondDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is a valid CNPJ..
        /// </summary>
        public static string isCNPJ_success {
            get {
                return ResourceManager.GetString("isCNPJ_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string isCPF_error_default {
            get {
                return ResourceManager.GetString("isCPF_error_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first digit of value is not equal to the first digit verifier..
        /// </summary>
        public static string isCPF_error_firstDigit {
            get {
                return ResourceManager.GetString("isCPF_error_firstDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value contain invalid characters..
        /// </summary>
        public static string isCPF_error_invalidCharacters {
            get {
                return ResourceManager.GetString("isCPF_error_invalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is a known invalid CPF..
        /// </summary>
        public static string isCPF_error_knownInvalid {
            get {
                return ResourceManager.GetString("isCPF_error_knownInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value does not contains eleven characters..
        /// </summary>
        public static string isCPF_error_notElevenCharacters {
            get {
                return ResourceManager.GetString("isCPF_error_notElevenCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is null or empty..
        /// </summary>
        public static string isCPF_error_nullOrEmpty {
            get {
                return ResourceManager.GetString("isCPF_error_nullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second digit of value is not equal to the second digit verifier..
        /// </summary>
        public static string isCPF_error_secondDigit {
            get {
                return ResourceManager.GetString("isCPF_error_secondDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is a valid CPF..
        /// </summary>
        public static string isCPF_success {
            get {
                return ResourceManager.GetString("isCPF_success", resourceCulture);
            }
        }
    }
}
